name: Build and Publish VS Code Extension

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.0

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22' # Specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the extension
      run: npm run compile # or any command you use to build your extension

    - name: Package the extension
      run: npx vsce package

    - name: Read package version
      id: version_step
      run: echo "PACKAGE_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

    - name: Create Release Asset
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: cctweaked-intellisense-${{ env.PACKAGE_VERSION }}
        path: '*.vsix' # Adjust this if your VSIX filename is different

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.0

    - name: Read package version
      id: version_step
      run: echo "PACKAGE_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

    - name: Download Release Asset
      uses: actions/download-artifact@v3.0.2
      with:
        name: cctweaked-intellisense-${{ env.PACKAGE_VERSION }}
        path: ./ # This will download the artifact to the current directory

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.PACKAGE_VERSION }}
        draft: false
        fail_on_unmatched_files: true
        prerelease: false
        files: cctweaked-intellisense-${{ env.PACKAGE_VERSION }}.vsix
        token: ${{ secrets.GITHUB_TOKEN }}
        make_latest: true
